# SpawnShield Config

# The list of regions to block entry into in combat
# This option can be controlled by the command /spawnshield block command
# Please use the command to edit this option, as it checks for errors when you add them
blockRegions:
  - "example"
  - "example2"

# The prevention mode to put the plugin in
# 'teleport' teleports the player to their last known location outside of the safezone if they enter a safezone
# 'knockback' knocks the player back when they enter a safezone
# 'forcefield' shows red glass around the border of blocked regions (spawn) to prevent players from entering
mode: "forcefield"

# Print out a ****load of information about the plugin
# You probably shouldn't use this unless you are testing the plugin
debug: false

# The time (in seconds) after their combat tag has expired, that they still are blocked from spawn
afterCombatDelay: 0

# ForceField settings
force-field:
  # The radius around which players will see a forcefield
  range: 50