name: "SpawnShield"
version: 1.1.0
main: net.techcable.spawnshield.SpawnShield
authors:
  - Techcable
commands:
  spawnshield:
    description: "The plugin's main command"
permissions:
  spawnshield.block:
    default: op
    description: "Allows you to use the /spawnshield block command"
softdepend:
  - PvPManager
  - CombatTag
  - CombatTagPlus
depend:
  - WorldGuard
